[project]
authors = ["Joshua Siraj <joshua.siraj@uhn.ca>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "IterSeg"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "==3.12"

[pypi-dependencies]
nnunetv2 = ">=2.6.0, <3"
med-imagetools = ">=2.9.1, <3"
damply = ">=0.16.0, <0.17"

